### ISSUE TITLE
du huan

### ISSUE THREAD

**Issue by GitNether** [LmaoPewPew/KonveratusApperatus#2]
BEST APP EVER

**Comment by LmaoPewPew** [comment]
> dier devlopr kould yu plis cange te name of the app?
> 
> copiryght claim will follow

please practise your english skills via Duolingo or other english practising portals.

nonetheless the Application name is 100% brought up to my teams and mine Imagination, if you do have further complains about such false accusations please concider shuting your mouth.

with best regarts



Dev Team LmaoPewPew

**Comment by bircni** [comment]
BEST APP EVER
